USE [TicketMaster] 
GO 
/****** Object: Table [dbo].[Table_1] Script Date: 28/08/2017 09:45:32 p.m. ******/ 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Table_1]') AND type in (N'U')) 
DROP TABLE [dbo].[Table_1] 
GO 
USE [master] 
GO 
/****** Object: Database [TicketMaster] Script Date: 28/08/2017 09:45:32 p.m. ******/ 
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'TicketMaster') 
DROP DATABASE [TicketMaster] 
GO 
/****** Object: Database [TicketMaster] Script Date: 28/08/2017 09:45:32 p.m. ******/ 
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'TicketMaster') 
BEGIN 
CREATE DATABASE [TicketMaster] 
GO 

ALTER DATABASE [TicketMaster] SET COMPATIBILITY_LEVEL = 110 
GO 
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled')) 
begin 
EXEC [TicketMaster].[dbo].[sp_fulltext_database] @action = 'enable' 
end 
GO 
ALTER DATABASE [TicketMaster] SET ANSI_NULL_DEFAULT OFF 
GO 
ALTER DATABASE [TicketMaster] SET ANSI_NULLS OFF 
GO 
ALTER DATABASE [TicketMaster] SET ANSI_PADDING OFF 
GO 
ALTER DATABASE [TicketMaster] SET ANSI_WARNINGS OFF 
GO 
ALTER DATABASE [TicketMaster] SET ARITHABORT OFF 
GO 
ALTER DATABASE [TicketMaster] SET AUTO_CLOSE OFF 
GO 
ALTER DATABASE [TicketMaster] SET AUTO_CREATE_STATISTICS ON 
GO 
ALTER DATABASE [TicketMaster] SET AUTO_SHRINK OFF 
GO 
ALTER DATABASE [TicketMaster] SET AUTO_UPDATE_STATISTICS ON 
GO 
ALTER DATABASE [TicketMaster] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO 
ALTER DATABASE [TicketMaster] SET CURSOR_DEFAULT GLOBAL 
GO 
ALTER DATABASE [TicketMaster] SET CONCAT_NULL_YIELDS_NULL OFF 
GO 
ALTER DATABASE [TicketMaster] SET NUMERIC_ROUNDABORT OFF 
GO 
ALTER DATABASE [TicketMaster] SET QUOTED_IDENTIFIER OFF 
GO 
ALTER DATABASE [TicketMaster] SET RECURSIVE_TRIGGERS OFF 
GO 
ALTER DATABASE [TicketMaster] SET DISABLE_BROKER 
GO 
ALTER DATABASE [TicketMaster] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO 
ALTER DATABASE [TicketMaster] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO 
ALTER DATABASE [TicketMaster] SET TRUSTWORTHY OFF 
GO 
ALTER DATABASE [TicketMaster] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO 
ALTER DATABASE [TicketMaster] SET PARAMETERIZATION SIMPLE 
GO 
ALTER DATABASE [TicketMaster] SET READ_COMMITTED_SNAPSHOT OFF 
GO 
ALTER DATABASE [TicketMaster] SET HONOR_BROKER_PRIORITY OFF 
GO 
ALTER DATABASE [TicketMaster] SET RECOVERY SIMPLE 
GO 
ALTER DATABASE [TicketMaster] SET MULTI_USER 
GO 
ALTER DATABASE [TicketMaster] SET PAGE_VERIFY CHECKSUM 
GO 
ALTER DATABASE [TicketMaster] SET DB_CHAINING OFF 
GO 
ALTER DATABASE [TicketMaster] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO 
ALTER DATABASE [TicketMaster] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO 
USE [TicketMaster] 
GO 
/****** Object: Table [dbo].[Table_1] Script Date: 28/08/2017 09:45:32 p.m. ******/ 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Table_1]') AND type in (N'U')) 
BEGIN 
CREATE TABLE [dbo].[Table_1]( 
[g] [nchar](10) NULL 
) ON [PRIMARY] 
END 
GO 
USE [master] 
GO 
ALTER DATABASE [TicketMaster] SET READ_WRITE 
GO 

/****** AngelxPM ******/ 